export const commentsOnPR = [
  "Looks great, but can we make the code more aerodynamic?",
  "I'm 99.9% sure this code will work. Let's leave the rest to luck!",
  "I've added some code that magically turns bugs into unicorns 🦄",
  "This code is so efficient, it runs on a potato 🥔",
  "I've implemented a feature that automatically refills your coffee cup ☕️",
  "Code reviewed while balancing a spoon on my nose. Approved!",
  "I've added a 'feature' that turns the screen upside down every 10 minutes. Just for fun.",
  "This code is so clean, I can eat my lunch off it 🍽️",
  "Implemented a 'Dance Party' mode. Just add music and watch the code boogie!",
  "I'm 50% confident that this code will work 50% of the time.",
  "Warning: This code contains traces of unicorn glitter. Handle with care 🌈✨",
  "I've added a 'Random Cat Facts' feature. Because why not?",
  "Incorporated a 'Chaos Monkey' mode. Let's see what happens!",
  "Just added some duct tape and WD-40. Code should be good to go!",
  "Enhanced the code with a 'Rickroll' feature. Enjoy the surprise!",
  "I've sprinkled some magic 'debugging dust' on this code. It's foolproof now!",
  "Implemented a 'Reverse Gravity' mode. Just for the thrill.",
  "This code is so elegant, it's practically wearing a top hat 🎩",
  "I've added a 'Chocolate Dispenser' feature. Who said coding can't be sweet?",
  "Code approved after a rigorous battle with a rubber chicken 🐔",
  "Tried to make the code as user-friendly as talking to a penguin 🐧",
  "I've added a 'Self-Destruct' button. Handle with extreme caution!",
  "This code is like a fine wine – it gets better with age 🍷",
  "I've implemented a 'Magic 8 Ball' feature for all your decision-making needs 🎱",
  "Code optimized for running on a potato-powered server 🥔",
  "Tried to make the code as stable as a table with three legs.",
  "I've added a 'Time Travel' feature. Use at your own risk!",
  "Just added some 'Flux Capacitor' code. Let's go back to the future!",
  "Code reviewed and endorsed by a team of highly trained squirrels 🐿️",
  "I've added a 'Bananaphone' feature. Ring, ring, ring, ring, ring, ring, banana phone!",
  "Code now comes with a 'Spaghetti Mode' option. Tangle up your logic!",
  "I've added a 'Dramatic Exit' feature. Because every code needs a grand finale!",
  "Code polished to a shine brighter than a disco ball 🕺",
  "I've added a 'Fancy Pants' mode. Code now wears a monocle and top hat.",
  "This code is so good, it deserves its own fan club 🎉",
  "I've added a '404' feature. Just in case the code gets lost.",
  "Code reviewed and approved by a committee of rubber ducks 🦆",
  "I've added a 'Breakfast in Bed' feature. Code now serves pancakes!",
  "Just sprinkled some 'Fairy Dust' on the code. It's practically magical now!",
  "Code upgraded with a 'Disco Inferno' mode. Burn, baby, burn!",
  "I've added a 'Dinosaur Rampage' feature. Run for your lives!",
  "Code certified by the Ministry of Silly Walks 🚶‍♂️",
  "Just added some 'Easter Egg' code. Can you find them all?",
  "Code is now certified organic, gluten-free, and locally sourced 🌱",
  "I've added a 'Clown Car' feature. How many clowns can we fit in this code?",
  "Code polished to a shine brighter than a diamond 💎",
  "I've added a 'Kitten Cannon' feature. Aim, fire, meow!",
  "Just added a 'Nyan Cat' feature. Code now leaves a rainbow trail!",
  "Code now comes with a 'Mystery Flavor' option. What will you discover?",
  "I've added a 'Squirrel Rampage' feature. Acorns everywhere!",
  "Code reviewed and approved by the Ghostbusters 👻",
  "Just added a 'Pirate Speak' feature. Avast ye, matey!",
  "Code now comes with a 'Taco Tuesday' reminder. Don't forget the guac!",
  "I've added a 'Zombie Apocalypse' feature. Grab your brains and run!",
  "Code now certified as 'Llama Approved' 🦙",
  "Just added some 'Fairy Tale' code. Once upon a time in a repo far, far away...",
  "Code upgraded with a 'Robot Overlord' mode. Bow down to your code masters!",
  "I've added a 'Jellybean Rain' feature. Catch 'em all!",
  "Code now sings 'Bohemian Rhapsody' on loop 🎶",
  "Just added a 'Fluffy Bunny' feature. Code now comes with extra hop!",
  "Code now has a 'Secret Agent' mode. Shaken, not stirred.",
  "I've added a 'Cupcake Cannon' feature. Sprinkles everywhere!",
  "Code now certified by the International Association of Puppies 🐶",
  "Just added some 'Feng Shui' code. Balance and harmony achieved!",
  "Code now speaks fluent Klingon. Qapla'!",
  "I've added a 'Ninja Stealth' mode. Code now moves in silence.",
  "Code reviewed and approved by the Knights of the Round Table 🏰",
  "Just added some 'Bubble Wrap' code. Ready for some popping fun?",
  "Code now comes with a 'Pot of Gold' feature. Finders keepers!",
  "I've added a 'Penguin Parade' feature. Waddle, waddle, waddle!",
  "Code now certified as 'Cosmic Dust' resistant ✨",
  "Just added some 'Marshmallow Fluff' code. Sweet and fluffy!",
  "Code now dances the Macarena on Fridays 💃",
  "I've added a 'Rainbow Bridge' feature. Cross over to the land of unicorns!",
  "Code now sings karaoke. Pick a song and join the party!",
  "Just added some 'Moon Cheese' code. For that out-of-this-world taste!",
  "Code now certified as 'Sasquatch Approved' 🦥",
  "I've added a 'Magic Carpet Ride' feature. Soar through the clouds!",
  "Code now comes with a 'Troll Bridge' feature. Pay the toll or face the troll!",
  "Just added some 'Sunshine and Rainbows' code. Embrace the positivity!",
  "Code now performs magic tricks. Abracadabra!",
  "I've added a 'Fairy Godmother' feature. Make your wishes come true!",
  "Code now certified as 'Bigfoot Resistant' 🦶",
  "Just added a 'Leprechaun Gold' feature. Find the end of the rainbow!",
  "Code now grants three wishes. Choose wisely!",
  "I've added a 'Unicorn Stampede' feature. Sparkle and gallop away!",
  "Code now certified by the International Association of Wizards 🧙‍♂️",
  "Just added some 'Fairy Wings' code. Fly away to magical lands!",
  "Code now has a 'Mermaid Lagoon' feature. Dive deep into adventure!",
  "I've added a 'Dragon Roar' feature. Fire-breathing fun!",
  "Code now certified as 'Nessie Proof' 🐉",
  "Just added a 'Goblin Market' feature. Buy, sell, and trade with goblins!",
  "Code now comes with a 'Magic Wand' feature. Cast your spells!",
  "I've added a 'Centaur Stampede' feature. Hooves pounding, hearts racing!",
  "Code now certified by the Society of Wizards and Warlocks 🧙‍♀️",
  "Just added some 'Pixie Dust' code. Sprinkle and sparkle!",
  "Code now has a 'Griffin Nest' feature. Guarded by majestic beasts!",
  "I've added a 'Witch's Brew' feature. Stir up some magic!",
  "Code now certified as 'Ogre Resistant' 💪",
  "Just added a 'Fairy Tale Ending' feature. Happily ever after guaranteed!",
];
